image_width: 640 # 1280
image_height: 480 # 720
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [790.48048,    0.     ,  315.943760,
            0.     , 789.493581,  240.843502,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.006117, -0.055067, 0.000862, 0.007062, 0.000000]
